### ISSUE TITLE
Properties omitted from nested objects 

### ISSUE THREAD

**Issue by alwaysbemark** [thim81/openapi-format#126]
Hello! At first glance, it looks like when a schema is defined with a particular name (`user` in this case), the property is omitted from other objects when openapi-filter is run even if those other objects don't refer to that schema.

For example, this is our OpenAPI file:

```
{
  "openapi" : "3.0.2",
  "info" : {
    "contact" : {
      "url" : ""
    },
    "description" : "",
    "title" : "",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : ""
  } ],
  "paths" : {
    "/jobs" : {
      "post" : {
        "description" : "New job",
        "operationId" : "createJob",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/job-request"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "type": "string"
                }
              }
            },
            "description" : "OK"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "user" : {
        "properties" : {
          "email" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          }
        },
        "required" : [ "email", "name" ],
        "type" : "object"
      },
      "job-request" : {
        "additionalProperties" : false,
        "properties" : {
          "projectId" : {
            "type" : "string"
          },
          "details" : {
            "$ref" : "#/components/schemas/details"
          }
        },
        "required" : [ "details" ],
        "type" : "object"
      },
      "details" : {
        "additionalProperties" : false,
        "properties" : {
          "user" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          }
        },
        "required" : [ "user", "password" ],
        "type" : "object"
      }
    }
  }
}
```

and filter file:

```
unusedComponents:
  - schemas
  - parameters
  - examples
  - headers
  - requestBodies
  - responses
inverseOperationIds:
  - createJob
```

Results in an OpenAPI spec where the `details` object does not have the `user` property, even though the latter is just a string property and has nothing to do with the `components/schemas/user` schema defined earlier. The original OpenAPI spec has both a `user` and a `password` properties inside `details`.

```
"details": {
        "type": "object",
        "properties": {
          "password": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "user",
          "password"
        ]
      }
```

Thanks for the amazing library!

**Comment by thim81** [comment]
hi @alwaysbemark 

The combination of inverse filtering and unusedComponents, is filtering out too much.
We have spend some time to find the cause, but not able to find the root cause yet.

It is partially linked to #106, we will use your provided input to include in our investigation.

We will keep you posted if we have an update.

**Comment by thim81** [comment]
@alwaysbemark 

I created a [playground](https://openapi-format-playground.vercel.app/?input=H4sIAAAAAAAAA6VTTVPCMBC98ys61WOlFW8evakz6p3hENpFwpQkZoMMw%2FS%2FuwmlX2mV4qXT7Ofbt2%2BPkyAIpQLBFA8fg%2FBhmkxnYWStXKwkmY70T69UCsNSUxnItNO5TQndu4hOcRlgqrkyXArnLM2Gmxyahm%2FQWMbcU8%2FEVnE1QgRtneSZu9CBfvRduHjFzBproPFGLrEJU0lswvYxvsE%2BoKQSmYsgRjSz%2FufMRqQamIGXdoyGrx2geZLZoVW%2BJAuE6ZjJwZTKeeoqxxt07dsRdv50DVvW4yHfrYaVBXQTp3KrpKAmGJ8S0A5%2BV4IKO6nFZOhVRE3gNp1rsEMbvYNJTxTFIHVGwO7UsyTxJx6i4jIyfqfD6uqgnKzQaC4%2Bu2N3B%2FeIiNpgO8J4f20WrFPPf0WlxJNy653UciyX07obUnhbkEpbwRnuc0q5PPdZHR67vU%2FBtjAqe2DjlSrmPji%2FYWVYNIqcm8rlBtJKoFWbsKneFjksy7jdCMs%2FmjStWI4QXcIheWxLd8pX8piBoVG7lf86yHPW1QR7BcYQ2of5%2F2R64h3Fo2KIe6nHbWIUZQ5ff88xLNaXPSl%2BAEXcDAUkBwAA&config=H4sIAAAAAAAAA2WQTWrDQAyFr2K09gmybKDQUMjCy04XaqzYU8bSdKQphZC7R%2BPQEtOlvqef93QBlWKwO2NS6uEck1EZyAlcAnddgMjfVJSOmQpaFH4ZNcCue2tq00%2BF0OggHwEaeu%2FvY5Wr0riXJQsT23ZGTzMt6Kz%2FJRkLLuS3HyH94JITPaKZcNw2FfqqpPYkY6QtVz%2Btja2%2BAl%2BhX9Pe43kR9XnNe8wtmO4lJczu%2Bu8dUQfv%2Fy9bqa5KtVztFXmqOJGv%2FFRhX5vR5mH9KkiJU2RMcL0BEQqhdGkBAAA%3D) of your provided filter and openapi doc

On the screenshot of the Diff, I indicated what should be kept:
<img width="1746" alt="image" src="https://github.com/user-attachments/assets/d504ef79-a4bb-4958-9fec-38584edd97ee">

Is that correct?

**Comment by alwaysbemark** [comment]
> @alwaysbemark 
> 
> 
> 
> I created a [playground](https://openapi-format-playground.vercel.app/?input=H4sIAAAAAAAAA6VTTVPCMBC98ys61WOlFW8evakz6p3hENpFwpQkZoMMw%2FS%2FuwmlX2mV4qXT7Ofbt2%2BPkyAIpQLBFA8fg%2FBhmkxnYWStXKwkmY70T69UCsNSUxnItNO5TQndu4hOcRlgqrkyXArnLM2Gmxyahm%2FQWMbcU8%2FEVnE1QgRtneSZu9CBfvRduHjFzBproPFGLrEJU0lswvYxvsE%2BoKQSmYsgRjSz%2FufMRqQamIGXdoyGrx2geZLZoVW%2BJAuE6ZjJwZTKeeoqxxt07dsRdv50DVvW4yHfrYaVBXQTp3KrpKAmGJ8S0A5%2BV4IKO6nFZOhVRE3gNp1rsEMbvYNJTxTFIHVGwO7UsyTxJx6i4jIyfqfD6uqgnKzQaC4%2Bu2N3B%2FeIiNpgO8J4f20WrFPPf0WlxJNy653UciyX07obUnhbkEpbwRnuc0q5PPdZHR67vU%2FBtjAqe2DjlSrmPji%2FYWVYNIqcm8rlBtJKoFWbsKneFjksy7jdCMs%2FmjStWI4QXcIheWxLd8pX8piBoVG7lf86yHPW1QR7BcYQ2of5%2F2R64h3Fo2KIe6nHbWIUZQ5ff88xLNaXPSl%2BAEXcDAUkBwAA&config=H4sIAAAAAAAAA2WQTWrDQAyFr2K09gmybKDQUMjCy04XaqzYU8bSdKQphZC7R%2BPQEtOlvqef93QBlWKwO2NS6uEck1EZyAlcAnddgMjfVJSOmQpaFH4ZNcCue2tq00%2BF0OggHwEaeu%2FvY5Wr0riXJQsT23ZGTzMt6Kz%2FJRkLLuS3HyH94JITPaKZcNw2FfqqpPYkY6QtVz%2Btja2%2BAl%2BhX9Pe43kR9XnNe8wtmO4lJczu%2Bu8dUQfv%2Fy9bqa5KtVztFXmqOJGv%2FFRhX5vR5mH9KkiJU2RMcL0BEQqhdGkBAAA%3D) of your provided filter and openapi doc
> 
> 
> 
> On the screenshot of the Diff, I indicated what should be kept:
> 
> <img width="1746" alt="image" src="https://github.com/user-attachments/assets/d504ef79-a4bb-4958-9fec-38584edd97ee">
> 
> 
> 
> Is that correct?

Yeah @thim81 that is what we expected. Thank you!

**Comment by thim81** [comment]
hi @alwaysbemark,

I found the reason and created a new version 1.22.3 that solves the too aggressive filtering of unused components.
With the help of your clear example, it was easy to debug and spot, so thanks for taking the time to provide theses details.

You can see the result in the [playground](https://openapi-format-playground.vercel.app/?input=H4sIAAAAAAAAA6VTTVPCMBC98ys61WOlFW8evakz6p3hENpFwpQkZoMMw%2FS%2FuwmlX2mV4qXT7Ofbt2%2BPkyAIpQLBFA8fg%2FBhmkxnYWStXKwkmY70T69UCsNSUxnItNO5TQndu4hOcRlgqrkyXArnLM2Gmxyahm%2FQWMbcU8%2FEVnE1QgRtneSZu9CBfvRduHjFzBproPFGLrEJU0lswvYxvsE%2BoKQSmYsgRjSz%2FufMRqQamIGXdoyGrx2geZLZoVW%2BJAuE6ZjJwZTKeeoqxxt07dsRdv50DVvW4yHfrYaVBXQTp3KrpKAmGJ8S0A5%2BV4IKO6nFZOhVRE3gNp1rsEMbvYNJTxTFIHVGwO7UsyTxJx6i4jIyfqfD6uqgnKzQaC4%2Bu2N3B%2FeIiNpgO8J4f20WrFPPf0WlxJNy653UciyX07obUnhbkEpbwRnuc0q5PPdZHR67vU%2FBtjAqe2DjlSrmPji%2FYWVYNIqcm8rlBtJKoFWbsKneFjksy7jdCMs%2FmjStWI4QXcIheWxLd8pX8piBoVG7lf86yHPW1QR7BcYQ2of5%2F2R64h3Fo2KIe6nHbWIUZQ5ff88xLNaXPSl%2BAEXcDAUkBwAA&config=H4sIAAAAAAAAA2WQTWrDQAyFr2K09gmybKDQUMjCy04XaqzYU8bSdKQphZC7R%2BPQEtOlvqef93QBlWKwO2NS6uEck1EZyAlcAnddgMjfVJSOmQpaFH4ZNcCue2tq00%2BF0OggHwEaeu%2FvY5Wr0riXJQsT23ZGTzMt6Kz%2FJRkLLuS3HyH94JITPaKZcNw2FfqqpPYkY6QtVz%2Btja2%2BAl%2BhX9Pe43kR9XnNe8wtmO4lJczu%2Bu8dUQfv%2Fy9bqa5KtVztFXmqOJGv%2FFRhX5vR5mH9KkiJU2RMcL0BEQqhdGkBAAA%3D)
