### ISSUE TITLE
Deletes paths with only 'head' operation

### ISSUE THREAD

**Issue by miriamgreis** [thim81/openapi-format#128]
The filtering deletes any paths which only have a `head` operation and no other operation. We, however, need to have paths with only `head` operations in our project although it might be a rather uncommon use case.

The problem seems to be in the `openapi-format.js` in line 158 where `head` is not included in the list of `httpVerbs`.

**Comment by thim81** [comment]
hi @miriamgreis 

You are correct. OpenAPI 3.0 supports get, post, put, patch, delete, head, options, and trace. 
I'll extend the httpVerbs options with `HEAD` and also`OPTIONS`, `TRACE`.

Thanks for bringing it my attention.

**Comment by thim81** [comment]
FYI: The [PR](#129) is ready and will probably land today.

**Comment by miriamgreis** [comment]
> @miriamgreis
> 
> I assume you want to do the "inverseMethods"?

No, I just wanted to filter for some flags and suddenly some operations were completely gone. But I tried with these filters then as well and also realised that even they don't work as I would expect it.

**Comment by thim81** [comment]
hmm 🤔 
Can you share your filter config?

I extended the httpVerbs list in the PR, but wanted to double check that it solves your mentioned case.

**Comment by miriamgreis** [comment]
> hmm 🤔 Can you share your filter config?
> 
> I extended the httpVerbs list in the PR, but want to double check that it solves your mentioned case.

It was really just as easy as this:
```
flags:
  - x-exclude
```

I think the problem is line 625ff. Because based on the `httpVerbs`, it deletes all paths that don't have any verb from the list.

**Comment by thim81** [comment]
I extended a test with flags and the PR fixes your issue.

**Comment by thim81** [comment]
hi @miriamgreis 

I just release openapi-format to version 1.22.4, you can test on the [playground](https://openapi-format-playground.vercel.app/?config=H4sIAAAAAAAAA2WOsQoCMQyGX6VkvnuBroKT4NDVJXhpLcS2NCmciO9u7I2OSb7%2Fy%2F8GqV3Bax%2B0QMys1APZAiJjEn8rzq1uX2m%2F89gIlskfhA1ZzjNybZprkVNlxia0gY%2FIQj8gGP9%2FPv7VoW3oBUsamMiUL3yyaRvqI8xeUHtOuSDD5wsNIx9zqwAAAA%3D%3D) if the latest version fixes your problem with the "head".

Portman and openapi-format have different release cycles, so best is to bump openapi-format in your package.json to use the latest version.
