### ISSUE TITLE
sortSet in new combinde config file do not take effect

### ISSUE THREAD

**Issue by bodograumann** [thim81/openapi-format#137]
When defining sortSet in `.openapiformatrc`, the `sortSet` option is disregarded.

Example .openapiformatrc:
```json
{
  "sort": true,
  "sortSet": {
    "root": ["paths", "openapi"]
  }
}
```

Now https://github.com/thim81/openapi-format/blob/main/bin/cli.js#L108-L114 overrides `sortSet` with settings from the default sort file.

**Comment by thim81** [comment]
hi @bodograumann 

I think I see the issue.

The expected behaviour would that the `sortSet `  defined `. openapiformatrc ` is applied and the default sorting is ignored?
Is that correct?

**Comment by bodograumann** [comment]
Exactly, otherwise using `sortSet` in `.openapiformatrc` would not be possible :-)

**Comment by thim81** [comment]
I'll have to wrap my head around it and create PR to fix this and tests to monitor it for future releases.

**Comment by thim81** [comment]
hi @bodograumann 

I think I have found a way to fix the resetting in this [PR](https://github.com/thim81/openapi-format/pull/138).
Expected is that this gets merged and shipped in the next openapi-format version, next week.

**Comment by thim81** [comment]
hi @bodograumann 

We just released openapi-format v1.23.1, it should keep the `. openapiformatrc` sort settings.

Can you verify, if this solves the behaviour in your setup?
If it is solved, feel free to close the issue.
If not, let me know, so we can further investigate options.

**Comment by bodograumann** [comment]
Yes that works! Thanks for the quick solution.

I had to add `"content": undefined` to my sortSet, because otherwise the attributes of a field called `"content"` where sorted alphabetically instead of semantically, but that is a different problem.

**Comment by thim81** [comment]
Interesting, Do you have a playground that showcases this sorting behaviour?
