### ISSUE TITLE
Playground white text visibility issues

### ISSUE THREAD

**Issue by vladshcherbin** [thim81/openapi-format#148]
Playground has white color text which is hard to see and is even impossible to read in some places:

<img width="1582" alt="image" src="https://github.com/user-attachments/assets/accd7e8f-b8fe-4589-9983-d5971f6c1285" />

macOS - 15.1.1
Chrome - Version 131.0.6778.109

I have dark appearance turned on on system level if this helps somehow 🙌

**Comment by thim81** [comment]
hi @vladshcherbin 

Thanks for reporting this, I was not aware of this.
Also the strange positioning of the buttons on the top left, is not how it supposed to look.

This is how it looks on my screen:
![IMG 2024-12-16 at 08 34 53@2x](https://github.com/user-attachments/assets/30f398a9-4a6a-4db7-a1db-80b4b666ce6c)

Can you also share which screen resolution you are using?

We are using Tailwind CSS so dark-mode and responsive layouts are easy to support.

**Comment by vladshcherbin** [comment]
@thim81 I'm using default resolution for macbook air 13, 1470 x  956

**Comment by thim81** [comment]
hi @vladshcherbin 

I just released a new version of the playground, that should handle the button positioning better and have better dark mode support.

**Comment by vladshcherbin** [comment]
@thim81 good to know, here's how it look on mine:

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/5764746a-c492-4da8-b410-b20684509528" />

Everything seems to be readable, selects are a bit hard since they are gray on white:

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/7772c962-ec0b-4b63-8e45-d168954a4bee" />

What do you think?

**Comment by thim81** [comment]
hi @vladshcherbin 

I tweaked the dark-mode styling a bit more, the white areas should be mostly gone.
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/7806269d-2c16-42f2-9c3d-e52423010b1d" />
<img width="1249" alt="image" src="https://github.com/user-attachments/assets/196f5cf1-96c0-48e5-b07f-30d0fc0a1992" />


Ok, for you?

**Comment by vladshcherbin** [comment]
@thim81 yes, the text is readable, thank you 🙌
