### ISSUE TITLE
Suggestion: Merge configuration files into one

### ISSUE THREAD

**Issue by wedi** [thim81/openapi-format#17]
It would be nice to have just one configuration file as seen in most tools.

It looks like `openapiformatrc[.(yaml|json)]` would follow a common pattern.

**Comment by thim81** [comment]
@wedi I ll make a PR as soon as I have some time. 

I ll make it a separate cli option, so that you can have the choice if you want to split the config or have 1 central file.

**Comment by thim81** [comment]
hi @wedi 

Long overdue, but in [release v1.23.0](https://github.com/thim81/openapi-format/releases/tag/v1.23.0), we introduced support for bundling all settings in the --configFile or .openapiformatrc. This allows you to define all OpenAPI-format options in a single file, which will be automatically detected.

For more details, check out the [readme](https://github.com/thim81/openapi-format?tab=readme-ov-file#cli-configuration-usage).

**Comment by thim81** [comment]
Closing this issue.

If you're still experiencing problems, please feel free to reopen this issue or create a new one. 
Thanks the suggestion and patience!
