### ISSUE TITLE
Suggestion: inverse filter

### ISSUE THREAD

**Issue by saoco** [thim81/openapi-format#18]
Hi,

I really love your tool. Especially, the sort options are very valuable in creating an easy diffable open api specification!

Still, there is one feature I am missing: an inverse filter option.

I don't want to have all of my operations in specification. Of course, I could use the already existing filter per operationId. Unfortunately, there are way more operations don't want to have in my specification than I want to have. 

Now, I would have to add all operations to the filter, except the ones that should remain. Plus each time, I add a new operation, I would need to touch the filter file again.

Having an inverse filter would make my live much easier.

What do you think? Would it be possible add this option to openapi-format?

Best

Christian

**Comment by thim81** [comment]
Hi @saoco

Thank you for taking the time to share your feedback. 

I fully understand the use case and adding it should be possible. 

Question: How would you want to configure it? Since you might want to mix the behaviour for pretty much all options.  

Idea:
Create inverse options for all filter options, which would allow you to filter out specific properties AND the inverse properties. Like: inverseFlags, inverseOperations

That way it might feel quite extensive and verbose to configure the filtering, but it give you all the flexibility to mix the filter behaviour. 

Feel free to share your opinion.

**Comment by thim81** [comment]
@saoco Until the inverse feature arrives, you could add a flag in your OpenAPI document, like 'x-exclude: true'

And then 'flags: ["x-exclude"]' as the filter. 

And by using 'stripFlags: ["x-exclude"]' the flag get removed as well, so end up with a clean and filter OpenAPI document.

**Comment by saoco** [comment]
@thim81 I like your idea of having the standard and the inverse option at the same time. I am just wondering what option should win. The normal one or the inverse one, if both refer to the same element?

I tend more towards the inverse filter should win. "Hiding" something is usually safer than exposing too much. What do you think?

Thanks for your proposal to use x-exclude.

My API is used by several consumers, each having a slightly different scope. My goal is to expose just the operations a consumer is really allowed to use. In my build pipeline, I would just need to exchange the configuration file (with according filter options) and I am done. Your idea would be perfect, if I would want to hide an API completely for all consumers, but that's not the case.

**Comment by thim81** [comment]
@saoco In the latest 1.7.0 release, I have introduced inverse filtering:
- for operationIds via `inverseOperationIds`
- for tags via `inverseTags`
- for methods via `inverseMethods`

This would help you to solve your use-cases. 

Closing this issue, but if you have more feedback, feel free to share.

**Comment by saoco** [comment]
@thim81 many, many thanks for this quick release!! This really helps me! :+1:

**Comment by thim81** [comment]
@saoco If you would have more feedback where that openapi-format can solve your use-cases, feel free to share it.
