### ISSUE TITLE
Node 12 Support broken

### ISSUE THREAD

**Issue by BerniWittmann** [thim81/openapi-format#21]
With commit https://github.com/thim81/openapi-format/commit/56713e7e7be7309937b21b8a42c3d2c19036ab52 this library started using more modern language features. 

This causes problems when running the library on node 12

Reproduction: 
```
# set node version 12
nvm use 12
# download petstore example
curl https://petstore3.swagger.io/api/v3/openapi.json --output ./tmp/docs-json 
# use library to convert
npx openapi-format ./tmp/docs-json
```

This result in the Error: `Unexpected token '.'` (To be exact bin/cli.js:143 `cliLog.unusedComp = resFilter?.resultData?.unusedComp;`

Doing the above on node 14 works flawlessly. 

I would advise to specify the [engines](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines) option in package.json and then install a compiler like [Babel](https://babeljs.io/) or sth. similar for easy compatibility with older node versions

In the meantime the workaround is to use node 14

**Comment by thim81** [comment]
@BerniWittmann 

Thank you for reporting the issue. I was not aware. 

I m no expert in Babel, so that is why I m trying to use simple JavaScript. 

Is the optional chaining the reason that node 14 is required?

**Comment by thim81** [comment]
@BerniWittmann 

In the 1.6.4 release of openapi-format, NodeJS 12 should be supported and the package is set to require minimum nodejs 12 to prevent future unclarity.

**Comment by BerniWittmann** [comment]
@thim81  Awesome, thank you very much. Especially thanks for the quick response 👍

**Comment by thim81** [comment]
@BerniWittmann Based on your feedback, we can make the package more stable, so thank you for taking the time to provide the feedback.
