### ISSUE TITLE
Empty security requirement ({}) is NOT supported.

### ISSUE THREAD

**Issue by lapinek** [thim81/openapi-format#23]
When an empty security requirement is used in an OpenAPI descriptor, the security option in a filtered descriptor is populated with incorrect value: `null`. 

Example:

* "openapi-format": "^1.6.4"

* A `security` definition in `example.yaml`:
    ```
    security:
        - BasicAuth: []
        - {}
    ```

* Formatting command:
    ```
    npx openapi-format example.yaml -o example.openapi-format.yaml --filterFile filter.json
    ```

* Content of `filter.json`:
    ```
    {
        "methods": [],
        "tags": [],
        "operationIds": [],
        "operations": [],
        "flags": [],
        "flagValues": [],
        "unusedComponents": [],
        "stripFlags": []
    }
    ```

 * The `security` definition in `example.openapi-format.yaml`:
    ```
    security:
        - BasicAuth: []
        - null
    ```

References:

* According to the spec, for both [OpenAPI Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#openapi-object) and [Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#operation-object) adding an empty schema object should be supported for making security optional:

   `security` > `[Security Requirement Object]`
    >  [ . . . ] To make security optional, an empty security requirement ({}) can be included in the array. [ . . . ]

* `null` does not appear to be a valid option for the Security Requirement Object:

    https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#optional-oauth2-security

***

In addition, filtering with the `--no-sort` option results in an error:
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v17.0.1
```

**Comment by thim81** [comment]
@lapinek Thanks for sharing the information about the optional Security Requirement Object. I was not aware of it.

In the latest release 1.7.0, I have fixed the handling the optional security object, so the "null" should not appear anymore. Th error that occurred with --no-sort error will also be gone, since both were related.

I have added test/example to make sure that we will track it in future version, to prevent regression.
https://github.com/thim81/openapi-format/tree/main/test/yaml-filter-security-empty
