### ISSUE TITLE
Sort file error - no such file or directory "defaultSort.json"

### ISSUE THREAD

**Issue by philipbjorge** [thim81/openapi-format#4]
I'm receiving this error whenever I run your tool.

```
Sort file error - no such file or directory "defaultSort.json"
```

It doesn't seem to be affecting anything as it completes and sorts my spec.
I've worked around by specifying `--sortFile ""`

---

Sorry, I don't have time to make a contribution here today -- But I wanted to let you know that I _really appreciate_ you building this tool. It's solving a real pain point for us in our large spec file and I'm amazed you're the first one to build/share something like this. Thanks!

**Comment by thim81** [comment]
Hi @philipbjorge 

Sorry for the inconvenience. The --sortFile parameter should be optional.

I want to make the experience as good as possible, can you provide me some information:
- the full command and parameters that you run to get this error
- if you run it on Windows or Mac or Linux machine

I assume you are using the latest version of the package.

Once, I have the input I'll try to reproduce the problem and try come with a fix.

**Comment by philipbjorge** [comment]
@thim81 - No inconvenience :) - Thank you for the tool.

The command:
`npx openapi-format descriptions/v1/api.yaml --output descriptions/v1/api.yaml`

Using `openapi-format@1.1.0`

---

I suspect the issue is...
1. `--sortFile` defaults to `defaultSort.json` - https://github.com/thim81/openapi-format/blob/main/bin/cli.js#L19
2. cli tries to read it and fails - https://github.com/thim81/openapi-format/blob/main/bin/cli.js#L90
3. Then the formatter loads up the defaultSort from the package - https://github.com/thim81/openapi-format/blob/main/openapi-format.js#L152

Cheers!

**Comment by thim81** [comment]
@philipbjorge You were right.

Thanks to your example, I was able to reproduce it and fix it.
I just pushed a new version (1.2.1) which solves this issue.
