### ISSUE TITLE
Sort paths by tags/operationId?

### ISSUE THREAD

**Issue by af-mikecrowe** [thim81/openapi-format#45]
Is it possible to sort the paths deterministically?  I'm thinking by tags then operationId?

**Comment by thim81** [comment]
Hi @af-mikecrowe 

Currently openapi-format sorts the elements within OpenAPI in a certain order, for example as defined in the [default](https://github.com/thim81/openapi-format/blob/main/defaultSort.json)

**Comment by af-mikecrowe** [comment]
Right -- My question: Is it possible to expand to sort another level down?  So, organize `paths` by Tag + OperationId, etc.

**Comment by thim81** [comment]
@af-mikecrowe 

I have to review the sorting logic, since currently it does 1 sort for all elements on 1 level.

**Comment by thim81** [comment]
hi @af-mikecrowe 

I added the option to sort paths alphabetically or by tag, by passing `--sortFile` with `sortPathsBy: tags`
Readme > https://github.com/thim81/openapi-format/tree/119-sort-path?tab=readme-ov-file#openapi-sort-paths
https://github.com/thim81/openapi-format/pull/121

You can play with it at the online playground https://openapi-format-playground.vercel.app/ and select on the left the desired paths ordering. 

![IMG-2024-08-06 at 11-14-10](https://github.com/user-attachments/assets/3cb91e3b-4c8e-4ce1-a349-5a57b3799510)

Would this solve your use-case?

**Comment by thim81** [comment]
linked to https://github.com/thim81/openapi-format/issues/119

**Comment by thim81** [comment]
Closing the issue.
We added option to sort by tags in [release 1.22.0](https://github.com/thim81/openapi-format/releases/tag/v1.22.0)
If you're still experiencing problems, please feel free to reopen this issue or create a new one. Thanks for your contribution!
