### ISSUE TITLE
`.d.ts` for TypeScript

### ISSUE THREAD

**Issue by eggplants** [thim81/openapi-format#51]
And if possible, please publish the d.ts file to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by thim81** [comment]
Hi @eggplants 

I'm not an expert in Typescript, could you explain me a bit more what is expected and what the `d.ts` file is used for?

**Comment by eggplants** [comment]
To use a node module made by javascript, `.d.ts` are needed.

**Comment by thim81** [comment]
hi @eggplants 

Did you ever solved the creation of the .d.ts defenition for openapi-format?
I'm looking into it and wondered how you solved it.

**Comment by thim81** [comment]
hi @eggplants 

I found this types.d.ts from @stijnvanhulle
https://github.com/kubb-labs/kubb/blob/main/packages/oas/src/typings.d.ts

Would that be what you expect?

**Comment by thim81** [comment]
For future reference:

The `.d.ts `types for OpenAPI format, used by the [openapi-format-playground](https://openapi-format-playground.vercel.app/) can be found: https://github.com/thim81/openapi-format-playground/blob/main/types/openapi-format.d.ts

Closing the issue.
