### ISSUE TITLE
Transformation of Number 

### ISSUE THREAD

**Issue by nicklloyd** [thim81/openapi-format#52]
Hi @thim81, we've seen that latest version, specifically [this commit](https://github.com/thim81/openapi-format/commit/32967d63ba8f7da5cff52daf8d497550fd067ec4), is affecting numbers used in escaped values. 

As an example, we use a vendor extension in our specs: 

```
      x-typescript-params: |-
        {
          id: 'id_example',
          payment: {
            currency: 'USD',
            currency_rate: 0.69,
            total_amount: 49.99,
            reference: '123456',
            payment_method: 'Credit Card',
            payment_method_reference: '123456'            
        }
```

Running 1.10.0 results is the following:

```
      x-typescript-params: |-
        {
          id: 'id_example',
          payment: {
            currency: 'USD',
            currency_rate: '0.69===',
            total_amount: '49.99===',
            reference: '123456',
            payment_method: 'Credit Card',
            payment_method_reference: '123456'            
        }
```

Maybe an edge case, but thought you should know

**Comment by thim81** [comment]
@nicklloyd thanks for reporting. I m working on a bug fix release for some unwanted conversion. I ll include this bug since this is clearly not desired.
