### ISSUE TITLE
Quotes around references to other files are incorrectly handled

### ISSUE THREAD

**Issue by florentausha** [thim81/openapi-format#98]
Hi,

When formatting this file, that has references to schemas defined in other files:  

```yaml
openapi: 3.1.0
info:
  title: Example
  version: 1.0.0
paths:
  /v1/examples:
    get:
      summary: Get
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Example'
components:
  schemas:
    Example:
      type: object
      properties:
        id:
          $ref: './otherfile.yaml#/components/schemas/Id'
```

The following command ` npx openapi-format ./public/docs/example.yaml -o ./public/docs/example.yaml`

Returns the following file:

```yaml
openapi: 3.1.0
info:
  title: Example
  version: 1.0.0
paths:
  /v1/examples:
    get:
      summary: Get
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Example'
components:
  schemas:
    Example:
      type: object
      properties:
        id:
          $ref: ./otherfile.yaml#/components/schemas/Id
```

As you can see, quotes around `$ref: './otherfile.yaml#/components/schemas/Id'` get removed.
Can I fix this by modifying my file?

**Comment by florentausha** [comment]
Temporarily fixed my issue by appending 
` sed -i '' "s/^\( *\$ref: \)\(.*\.yaml#\/.*\)$/\1'\2'/g" $filepath`
To every OpenAPI format command

**Comment by thim81** [comment]
hi @florentausha 

We use `@stoplight/yaml` for handling the YAML files, which manipulates the "".
https://github.com/thim81/openapi-format?tab=readme-ov-file#stoplight-studio

> We have adopted the YAML parsing style from [Stoplight Studio](https://stoplight.io/studio/), by leveraging the [@stoplight/yaml](https://www.npmjs.com/package/@stoplight/yaml) package for handling the parsing of OpenAPI YAML files.

> By using the Stoplight YAML parsing, the results will be slightly different from when using a normal YAML parsing library, like [js-to-yaml](https://www.npmjs.com/package/js-yaml). We appreciate the Stoplight Studio tool, since it is an excellent GUI for working with OpenAPI documents for non-OpenAPI experts who will be contributing changes. By adopting the Stoplight Studio YAML parsing, the potential risk of merge conflicts will be lowered, which is the main reason why we opted for using the @stoplight/yaml package.

**Comment by florentausha** [comment]
@thim81 Thanks for your detailed answer, I'll close this issue then 👍
